### ISSUE TITLE
 cannot import name '_TORCH_GREATER_EQUAL_1_13' from 'lightning_fabric.utilities.

### ISSUE THREAD

**Issue by laidingq** [kijai/ComfyUI-CCSR#3]
Traceback (most recent call last):
  File "D:\ComfyUI\nodes.py", line 1893, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\custom_nodes\ComfyUI-CCSR\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI\custom_nodes\ComfyUI-CCSR\nodes.py", line 8, in <module>
    from .model.ccsr_stage1 import ControlLDM
  File "D:\ComfyUI\custom_nodes\ComfyUI-CCSR\model\ccsr_stage1.py", line 18, in <module>
    from ..ldm.models.diffusion.ddpm_ccsr_stage1 import LatentDiffusion
  File "D:\ComfyUI\custom_nodes\ComfyUI-CCSR\ldm\models\diffusion\ddpm_ccsr_stage1.py", line 12, in <module>
    import pytorch_lightning as pl
  File "D:\ComfyUI\venv\Lib\site-packages\pytorch_lightning\__init__.py", line 27, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\venv\Lib\site-packages\pytorch_lightning\callbacks\__init__.py", line 29, in <module>
    from pytorch_lightning.callbacks.pruning import ModelPruning
  File "D:\ComfyUI\venv\Lib\site-packages\pytorch_lightning\callbacks\pruning.py", line 31, in <module>
    from pytorch_lightning.core.module import LightningModule
  File "D:\ComfyUI\venv\Lib\site-packages\pytorch_lightning\core\__init__.py", line 16, in <module>
    from pytorch_lightning.core.module import LightningModule
  File "D:\ComfyUI\venv\Lib\site-packages\pytorch_lightning\core\module.py", line 62, in <module>
    from pytorch_lightning.trainer import call
  File "D:\ComfyUI\venv\Lib\site-packages\pytorch_lightning\trainer\__init__.py", line 17, in <module>
    from pytorch_lightning.trainer.trainer import Trainer
  File "D:\ComfyUI\venv\Lib\site-packages\pytorch_lightning\trainer\trainer.py", line 46, in <module>
    from pytorch_lightning.loops import _PredictionLoop, _TrainingEpochLoop
  File "D:\ComfyUI\venv\Lib\site-packages\pytorch_lightning\loops\__init__.py", line 15, in <module>
    from pytorch_lightning.loops.evaluation_loop import _EvaluationLoop  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\venv\Lib\site-packages\pytorch_lightning\loops\evaluation_loop.py", line 29, in <module>
    from pytorch_lightning.loops.utilities import _no_grad_context, _select_data_fetcher, _verify_dataloader_idx_requirement
  File "D:\ComfyUI\venv\Lib\site-packages\pytorch_lightning\loops\utilities.py", line 24, in <module>
    from lightning_fabric.utilities.imports import _TORCH_EQUAL_2_0, _TORCH_GREATER_EQUAL_1_13
ImportError: cannot import name '_TORCH_GREATER_EQUAL_1_13' from 'lightning_fabric.utilities.imports' (D:\ComfyUI\venv\Lib\site-packages\lightning_fabric\utilities\imports.py)

Cannot import D:\ComfyUI\custom_nodes\ComfyUI-CCSR module for custom nodes: cannot import name '_TORCH_GREATER_EQUAL_1_13' from 'lightning_fabric.utilities.imports' (D:\ComfyUI\venv\Lib\site-packages\lightning_fabric\utilities\imports.py)

**Comment by f-rank** [comment]
Am getting the same thing. Had it installed previously and it ran ok, but after a clean install of comfyui and trying out AP Workflow 8.0, that needed it to be installed, it now fails with this same console output.

**Comment by f-rank** [comment]
@laidingq , do you happen to be using a direct repo of comfyui and NOT the portable version ?
Because I just tested and it works on a portable install and NOT on a direct repo. But could just be me.


> Traceback (most recent call last): File "D:\ComfyUI\nodes.py", line 1893, in load_custom_node module_spec.loader.exec_module(module) File "", line 940, in exec_module File "", line 241, in _call_with_frames_removed File "D:\ComfyUI\custom_nodes\ComfyUI-CCSR__init__.py", line 1, in from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS File "D:\ComfyUI\custom_nodes\ComfyUI-CCSR\nodes.py", line 8, in from .model.ccsr_stage1 import ControlLDM File "D:\ComfyUI\custom_nodes\ComfyUI-CCSR\model\ccsr_stage1.py", line 18, in from ..ldm.models.diffusion.ddpm_ccsr_stage1 import LatentDiffusion File "D:\ComfyUI\custom_nodes\ComfyUI-CCSR\ldm\models\diffusion\ddpm_ccsr_stage1.py", line 12, in import pytorch_lightning as pl File "D:\ComfyUI\venv\Lib\site-packages\pytorch_lightning__init__.py", line 27, in from pytorch_lightning.callbacks import Callback # noqa: E402 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\ComfyUI\venv\Lib\site-packages\pytorch_lightning\callbacks__init__.py", line 29, in from pytorch_lightning.callbacks.pruning import ModelPruning File "D:\ComfyUI\venv\Lib\site-packages\pytorch_lightning\callbacks\pruning.py", line 31, in from pytorch_lightning.core.module import LightningModule File "D:\ComfyUI\venv\Lib\site-packages\pytorch_lightning\core__init__.py", line 16, in from pytorch_lightning.core.module import LightningModule File "D:\ComfyUI\venv\Lib\site-packages\pytorch_lightning\core\module.py", line 62, in from pytorch_lightning.trainer import call File "D:\ComfyUI\venv\Lib\site-packages\pytorch_lightning\trainer__init__.py", line 17, in from pytorch_lightning.trainer.trainer import Trainer File "D:\ComfyUI\venv\Lib\site-packages\pytorch_lightning\trainer\trainer.py", line 46, in from pytorch_lightning.loops import _PredictionLoop, _TrainingEpochLoop File "D:\ComfyUI\venv\Lib\site-packages\pytorch_lightning\loops__init__.py", line 15, in from pytorch_lightning.loops.evaluation_loop import _EvaluationLoop # noqa: F401 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\ComfyUI\venv\Lib\site-packages\pytorch_lightning\loops\evaluation_loop.py", line 29, in from pytorch_lightning.loops.utilities import _no_grad_context, _select_data_fetcher, _verify_dataloader_idx_requirement File "D:\ComfyUI\venv\Lib\site-packages\pytorch_lightning\loops\utilities.py", line 24, in from lightning_fabric.utilities.imports import _TORCH_EQUAL_2_0, _TORCH_GREATER_EQUAL_1_13 ImportError: cannot import name '_TORCH_GREATER_EQUAL_1_13' from 'lightning_fabric.utilities.imports' (D:\ComfyUI\venv\Lib\site-packages\lightning_fabric\utilities\imports.py)
> 
> Cannot import D:\ComfyUI\custom_nodes\ComfyUI-CCSR module for custom nodes: cannot import name '_TORCH_GREATER_EQUAL_1_13' from 'lightning_fabric.utilities.imports' (D:\ComfyUI\venv\Lib\site-packages\lightning_fabric\utilities\imports.py)

**Comment by laidingq** [comment]
@f-rank I am using a direct repo and have not used a portable version before

**Comment by laidingq** [comment]
pytorch_righting==2.2.0 lightning_fabric==2.2.0，has been successfully installed

**Comment by f-rank** [comment]
@laidingq  Did it go through ?  Did you change something ?

> pytorch_righting==2.2.0 lightning_fabric==2.2.0，has been successfully installed

**Comment by laidingq** [comment]
@f-rank I just changed the pytorch_lighting and lighting_fabric versions to 0.2.0, nothing else changed,My Python is 311, torch2.12+cu121

**Comment by f-rank** [comment]
@laidingq thank you for explaining it. Fixed it.

> @f-rank I just changed the pytorch_lighting and lighting_fabric versions to 2.2.0, nothing else changed,Successfully installed and running without any errors,My Python is 311, torch2.12+cu121
